#!/bin/bash

# ============================================
# Syntra Environment Setup Script
# ============================================
# This script helps developers set up their environment variables
# after pulling the code from GitHub

set -e

echo "🚀 Syntra Environment Setup"
echo "============================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if .env files already exist
BACKEND_ENV="backend/.env"
FRONTEND_ENV="frontend/.env.local"

if [ -f "$BACKEND_ENV" ]; then
    echo -e "${YELLOW}⚠️  Backend .env already exists at $BACKEND_ENV${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping backend .env setup..."
        BACKEND_SKIP=true
    fi
fi

if [ -f "$FRONTEND_ENV" ]; then
    echo -e "${YELLOW}⚠️  Frontend .env.local already exists at $FRONTEND_ENV${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping frontend .env.local setup..."
        FRONTEND_SKIP=true
    fi
fi

# Setup backend .env
if [ -z "$BACKEND_SKIP" ]; then
    echo ""
    echo -e "${BLUE}📝 Setting up backend environment...${NC}"
    
    if [ -f "backend/env.example" ]; then
        cp backend/env.example "$BACKEND_ENV"
        echo -e "${GREEN}✅ Created $BACKEND_ENV from env.example${NC}"
        echo ""
        echo "⚠️  IMPORTANT: Edit $BACKEND_ENV and configure:"
        echo "   - DATABASE_URL (required)"
        echo "   - SECRET_KEY (required - generate a secure random string)"
        echo "   - ENCRYPTION_KEY (required - generate a Fernet key)"
        echo "   - QDRANT_URL (required)"
        echo "   - UPSTASH_REDIS_URL (required)"
        echo ""
        echo "Optional but recommended:"
        echo "   - OPENAI_API_KEY, GOOGLE_API_KEY, PERPLEXITY_API_KEY, etc."
        echo ""
    else
        echo -e "${YELLOW}⚠️  backend/env.example not found. Creating minimal .env...${NC}"
        cat > "$BACKEND_ENV" << EOF
# Backend Environment Variables
# Generated by setup-env.sh

# Database (REQUIRED)
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/syntra

# Qdrant (REQUIRED)
QDRANT_URL=http://localhost:6333
QDRANT_API_KEY=

# Redis (REQUIRED)
UPSTASH_REDIS_URL=redis://localhost:6379
UPSTASH_REDIS_TOKEN=

# Security (REQUIRED - CHANGE THESE!)
SECRET_KEY=dev-secret-key-change-this-in-production
ENCRYPTION_KEY=dev-encryption-key-change-this-in-production

# Frontend
FRONTEND_URL=http://localhost:3000

# Environment
ENVIRONMENT=development

# Optional: Provider API Keys
OPENAI_API_KEY=
GOOGLE_API_KEY=
PERPLEXITY_API_KEY=
KIMI_API_KEY=
EOF
        echo -e "${GREEN}✅ Created minimal $BACKEND_ENV${NC}"
    fi
fi

# Setup frontend .env.local
if [ -z "$FRONTEND_SKIP" ]; then
    echo ""
    echo -e "${BLUE}📝 Setting up frontend environment...${NC}"
    
    if [ -f "frontend/env.example" ]; then
        cp frontend/env.example "$FRONTEND_ENV"
        echo -e "${GREEN}✅ Created $FRONTEND_ENV from env.example${NC}"
        echo ""
        echo "⚠️  IMPORTANT: Edit $FRONTEND_ENV and configure:"
        echo "   - NEXT_PUBLIC_API_URL (required - backend API URL)"
        echo ""
        echo "Optional:"
        echo "   - Firebase configuration (if using Firebase auth)"
        echo ""
    else
        echo -e "${YELLOW}⚠️  frontend/env.example not found. Creating minimal .env.local...${NC}"
        cat > "$FRONTEND_ENV" << EOF
# Frontend Environment Variables
# Generated by setup-env.sh

# Backend API URL (REQUIRED)
NEXT_PUBLIC_API_URL=http://localhost:8000/api

# WebSocket URL (optional)
NEXT_PUBLIC_WS_URL=ws://localhost:8000
EOF
        echo -e "${GREEN}✅ Created minimal $FRONTEND_ENV${NC}"
    fi
fi

# Generate secure keys if requested
echo ""
read -p "Do you want to generate secure SECRET_KEY and ENCRYPTION_KEY? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    if command -v python3 &> /dev/null; then
        echo ""
        echo -e "${BLUE}🔐 Generating secure keys...${NC}"
        
        # Generate SECRET_KEY
        SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || echo "")
        
        # Generate ENCRYPTION_KEY (Fernet key)
        ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || echo "")
        
        if [ -n "$SECRET_KEY" ] && [ -n "$ENCRYPTION_KEY" ]; then
            if [ -f "$BACKEND_ENV" ]; then
                # Update the .env file
                if [[ "$OSTYPE" == "darwin"* ]]; then
                    # macOS
                    sed -i '' "s|SECRET_KEY=.*|SECRET_KEY=$SECRET_KEY|" "$BACKEND_ENV"
                    sed -i '' "s|ENCRYPTION_KEY=.*|ENCRYPTION_KEY=$ENCRYPTION_KEY|" "$BACKEND_ENV"
                else
                    # Linux
                    sed -i "s|SECRET_KEY=.*|SECRET_KEY=$SECRET_KEY|" "$BACKEND_ENV"
                    sed -i "s|ENCRYPTION_KEY=.*|ENCRYPTION_KEY=$ENCRYPTION_KEY|" "$BACKEND_ENV"
                fi
                echo -e "${GREEN}✅ Updated SECRET_KEY and ENCRYPTION_KEY in $BACKEND_ENV${NC}"
            else
                echo "Generated keys (add these to your backend/.env):"
                echo "SECRET_KEY=$SECRET_KEY"
                echo "ENCRYPTION_KEY=$ENCRYPTION_KEY"
            fi
        else
            echo -e "${YELLOW}⚠️  Could not generate keys. Make sure Python 3 and cryptography are installed.${NC}"
            echo "   Install: pip install cryptography"
        fi
    else
        echo -e "${YELLOW}⚠️  Python 3 not found. Skipping key generation.${NC}"
        echo "   You can generate keys manually using:"
        echo "   SECRET_KEY: python3 -c \"import secrets; print(secrets.token_urlsafe(32))\""
        echo "   ENCRYPTION_KEY: python3 -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    fi
fi

echo ""
echo -e "${GREEN}✅ Environment setup complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Review and edit backend/.env with your configuration"
echo "2. Review and edit frontend/.env.local with your backend API URL"
echo "3. Set up your database, Qdrant, and Redis instances"
echo "4. Add API keys for LLM providers (optional but recommended)"
echo ""
echo "For detailed instructions, see README.md"










